export const FEATURE_ITEMS = [
  { id: "domain", label: "My own web address (like yourname.com)", defaultOn: true },
  { id: "mobile", label: "Looks great on phones and tablets", defaultOn: true },
  { id: "contact", label: "Contact form so people can message me", defaultOn: true },
  { id: "map", label: "Map showing where my business is", defaultOn: true },
  { id: "booking", label: "Online booking or scheduling", defaultOn: false },
  { id: "gallery", label: "Photo gallery of my work", defaultOn: false },
  { id: "blog", label: "Blog or news updates", defaultOn: false },
  { id: "reviews", label: "Customer reviews and testimonials", defaultOn: false },
  { id: "pricing", label: "Pricing list or service packages", defaultOn: false },
  { id: "shop", label: "Sell products or take payments online", defaultOn: false },
  { id: "chat", label: "Live chat for quick questions", defaultOn: false },
  { id: "newsletter", label: "Email signup for updates", defaultOn: false },
  { id: "social", label: "Links to my social media", defaultOn: false },
];

export const THEME_OPTIONS = [
  { id: "ocean", label: "Ocean Blue", hint: "Calm and professional", colors: ["#2563eb", "#06b6d4"] },
  { id: "forest", label: "Forest Green", hint: "Natural and friendly", colors: ["#059669", "#84cc16"] },
  { id: "sunset", label: "Sunset Warm", hint: "Bold and welcoming", colors: ["#ea580c", "#ef4444"] },
  { id: "slate", label: "Modern Gray", hint: "Clean and minimal", colors: ["#475569", "#94a3b8"] },
  { id: "berry", label: "Berry Pink", hint: "Fun and creative", colors: ["#be185d", "#a855f7"] },
  { id: "mono", label: "Classic Black", hint: "Simple and timeless", colors: ["#18181b", "#71717a"] },
  { id: "coral", label: "Coral Pop", hint: "Bright and energetic", colors: ["#f43f5e", "#fb7185"] },
  { id: "lavender", label: "Lavender Dream", hint: "Soft and creative", colors: ["#7c3aed", "#c4b5fd"] },
  { id: "mint", label: "Fresh Mint", hint: "Cool and refreshing", colors: ["#10b981", "#6ee7b7"] },
  { id: "gold", label: "Golden Hour", hint: "Warm and premium", colors: ["#d97706", "#fbbf24"] },
  { id: "rose", label: "Rose Blush", hint: "Romantic and gentle", colors: ["#e11d48", "#fda4af"] },
  { id: "sky", label: "Sky Blue", hint: "Open and airy", colors: ["#0ea5e9", "#7dd3fc"] },
  { id: "lime", label: "Lime Zest", hint: "Fresh and upbeat", colors: ["#65a30d", "#bef264"] },
  { id: "plum", label: "Deep Plum", hint: "Rich and artistic", colors: ["#7e22ce", "#d8b4fe"] },
  { id: "teal", label: "Teal Wave", hint: "Modern and balanced", colors: ["#0d9488", "#5eead4"] },
  { id: "navy", label: "Navy Classic", hint: "Trustworthy and strong", colors: ["#1e3a8a", "#60a5fa"] },
  { id: "peach", label: "Peach Soft", hint: "Friendly and cozy", colors: ["#ea580c", "#fdba74"] },
  { id: "emerald", label: "Emerald Gem", hint: "Luxury and growth", colors: ["#047857", "#34d399"] },
  { id: "indigo", label: "Indigo Night", hint: "Deep and confident", colors: ["#4338ca", "#818cf8"] },
  { id: "aqua", label: "Aqua Splash", hint: "Tropical and fun", colors: ["#0891b2", "#67e8f9"] },
  { id: "cherry", label: "Cherry Red", hint: "Bold and memorable", colors: ["#be123c", "#f87171"] },
  { id: "sand", label: "Desert Sand", hint: "Earthy and warm", colors: ["#b45309", "#fcd34d"] },
  { id: "grape", label: "Grape Soda", hint: "Playful and vivid", colors: ["#6d28d9", "#a78bfa"] },
  { id: "rust", label: "Rustic Clay", hint: "Handmade and honest", colors: ["#c2410c", "#fb923c"] },
  { id: "magenta", label: "Hot Magenta", hint: "Eye-catching and bold", colors: ["#c026d3", "#f0abfc"] },
  { id: "cobalt", label: "Cobalt Bright", hint: "Vivid and confident", colors: ["#1d4ed8", "#3b82f6"] },
  { id: "sage", label: "Sage Garden", hint: "Calm and earthy", colors: ["#4d7c0f", "#84cc16"] },
  { id: "flame", label: "Flame Orange", hint: "Fiery and loud", colors: ["#dc2626", "#f97316"] },
  { id: "midnight", label: "Midnight Blue", hint: "Dark and sleek", colors: ["#172554", "#6366f1"] },
  { id: "fuchsia", label: "Fuchsia Pop", hint: "Neon and fun", colors: ["#c026d3", "#e879f9"] },
  { id: "charcoal", label: "Charcoal Smoke", hint: "Muted and modern", colors: ["#27272a", "#a1a1aa"] },
  { id: "salmon", label: "Salmon Pink", hint: "Soft and inviting", colors: ["#f43f5e", "#fecdd3"] },
  { id: "violet", label: "Violet Haze", hint: "Dreamy and artistic", colors: ["#5b21b6", "#c4b5fd"] },
  { id: "pistachio", label: "Pistachio Green", hint: "Light and fresh", colors: ["#16a34a", "#86efac"] },
  { id: "amber", label: "Amber Glow", hint: "Sunny and warm", colors: ["#d97706", "#fde047"] },
  { id: "crimson", label: "Crimson Wine", hint: "Rich and dramatic", colors: ["#991b1b", "#fca5a5"] },
  { id: "cerulean", label: "Cerulean Sky", hint: "Bright and hopeful", colors: ["#0284c7", "#7dd3fc"] },
  { id: "chartreuse", label: "Chartreuse Punch", hint: "Electric and bold", colors: ["#65a30d", "#d9f99d"] },
  { id: "orchid", label: "Orchid Bloom", hint: "Floral and feminine", colors: ["#a21caf", "#f0abfc"] },
  { id: "jade", label: "Jade Stone", hint: "Balanced and serene", colors: ["#0f766e", "#5eead4"] },
  { id: "sapphire", label: "Sapphire Deep", hint: "Prestige and depth", colors: ["#1e40af", "#93c5fd"] },
  { id: "apricot", label: "Apricot Warm", hint: "Sweet and cozy", colors: ["#ea580c", "#fed7aa"] },
  { id: "pine", label: "Pine Forest", hint: "Woodsy and grounded", colors: ["#166534", "#86efac"] },
  { id: "royal", label: "Royal Purple", hint: "Regal and elegant", colors: ["#581c87", "#c084fc"] },
  { id: "turquoise", label: "Turquoise Reef", hint: "Coastal and breezy", colors: ["#0e7490", "#67e8f9"] },
  { id: "wine", label: "Wine Red", hint: "Sophisticated and moody", colors: ["#7f1d1d", "#f87171"] },
  { id: "honey", label: "Honey Gold", hint: "Sweet and golden", colors: ["#ca8a04", "#fde68a"] },
  { id: "lilac", label: "Lilac Soft", hint: "Delicate and pretty", colors: ["#7c3aed", "#ddd6fe"] },
  { id: "copper", label: "Copper Shine", hint: "Metallic and warm", colors: ["#9a3412", "#fdba74"] },
  { id: "neon", label: "Neon Electric", hint: "High-energy and loud", colors: ["#16a34a", "#a3e635"] },
];

export const FONT_OPTIONS = [
  { id: "modern", label: "Clean & Simple", hint: "Easy to read", sample: "Inter" },
  { id: "editorial", label: "Warm & Personal", hint: "Story-driven", sample: "Fraunces" },
  { id: "classic", label: "Elegant", hint: "Premium feel", sample: "Playfair Display" },
  { id: "startup", label: "Bold & Modern", hint: "High energy", sample: "Space Grotesk" },
  { id: "friendly", label: "Friendly Round", hint: "Approachable", sample: "Nunito" },
  { id: "professional", label: "Professional", hint: "Trustworthy", sample: "Merriweather" },
  { id: "playful", label: "Playful Pop", hint: "Fun and young", sample: "Poppins" },
  { id: "magazine", label: "Magazine Bold", hint: "Headline impact", sample: "Oswald" },
  { id: "luxury", label: "Luxury Serif", hint: "High-end brand", sample: "Cormorant" },
  { id: "tech", label: "Tech Mono-Style", hint: "Clean and sharp", sample: "IBM Plex Sans" },
  { id: "coffee", label: "Coffee Shop", hint: "Cozy and relaxed", sample: "Lora" },
  { id: "soft", label: "Soft Rounded", hint: "Gentle and modern", sample: "Rubik" },
  { id: "retro", label: "Retro Classic", hint: "Old-school charm", sample: "Libre Baskerville" },
  { id: "minimal", label: "Ultra Minimal", hint: "Sleek and light", sample: "Manrope" },
  { id: "artsy", label: "Artsy Display", hint: "Creative standout", sample: "Abril Fatface" },
  { id: "urban", label: "Urban Street", hint: "Poster-style bold", sample: "Bebas Neue" },
  { id: "journal", label: "Reading Room", hint: "Bookish comfort", sample: "Literata" },
  { id: "handwriting", label: "Handwritten", hint: "Personal touch", sample: "Caveat" },
  { id: "newsroom", label: "Newsroom", hint: "Editorial clarity", sample: "Bitter" },
  { id: "runway", label: "Runway Chic", hint: "High fashion", sample: "Bodoni Moda" },
  { id: "boardroom", label: "Boardroom", hint: "Executive polish", sample: "Roboto Slab" },
  { id: "typewriter", label: "Typewriter", hint: "Retro writer", sample: "Special Elite" },
  { id: "signature", label: "Signature Script", hint: "Elegant script", sample: "Great Vibes" },
  { id: "geometric", label: "Geometric Clean", hint: "Modern shapes", sample: "Outfit" },
  { id: "industrial", label: "Industrial Slab", hint: "Strong headlines", sample: "Roboto Slab" },
  { id: "poster", label: "Poster Bold", hint: "All caps impact", sample: "Anton" },
  { id: "neo", label: "Neo Swiss", hint: "Minimal precision", sample: "Archivo" },
  { id: "botanic", label: "Botanic Serif", hint: "Nature inspired", sample: "Spectral" },
  { id: "cyber", label: "Cyber Future", hint: "Sci-fi edge", sample: "Exo 2" },
  { id: "cottage", label: "Cottage Warm", hint: "Homey charm", sample: "Crimson Pro" },
  { id: "stadium", label: "Stadium Power", hint: "Sports energy", sample: "Barlow" },
  { id: "bubble", label: "Bubble Fun", hint: "Playful script", sample: "Pacifico" },
];

export const THEME_LABELS = Object.fromEntries(THEME_OPTIONS.map((theme) => [theme.id, theme.label]));
export const FONT_LABELS = Object.fromEntries(FONT_OPTIONS.map((font) => [font.id, font.label]));
